In [ ]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time

import queue as qe

from sklearn.linear_model import LinearRegression

import networkx as nx

In [7]:
def fit_plot(l, func_2_fit, size_ini, size_fin, step):
    l_func_values =[i*func_2_fit(i) for i in range(size_ini, size_fin+1, step)]
    
    lr_m = LinearRegression()
    X = np.array(l_func_values).reshape( len(l_func_values), -1 )
    lr_m.fit(X, l)
    y_pred = lr_m.predict(X)
    
    plt.plot(l, '*', y_pred, '-')

def n2_log_n(n):
    return n**2. * np.log(n)

In [13]:
l = [
[0, 10, 1, np.inf],
[np.inf, 0, 1, np.inf],
[np.inf, np.inf, 0, 1 ],
[np.inf, 1, np.inf, 0]
]

m_g = np.array(l)

def print_m_g(m_g):
    print("graph_from_matrix:\n")
    n_v = m_g.shape[0]
    for u in range(n_v):
        for v in range(n_v):
            if v != u and m_g[u, v] != np.inf:
                print("(", u, v, ")", m_g[u, v])

d_g = {
0: {1: 10, 2: 1}, 
1: {2: 1}, 
2: {3: 1},
3: {1: 1}
}

def print_d_g(d_g):
    print("\ngraph_from_dict:\n")
    for u in d_g.keys():
        for v in d_g[u].keys():
            print("(", u, v, ")", d_g[u][v])

print_m_g(m_g)
print_d_g(d_g)

graph_from_matrix:

( 0 1 ) 10.0
( 0 2 ) 1.0
( 1 2 ) 1.0
( 2 3 ) 1.0
( 3 1 ) 1.0

graph_from_dict:

( 0 1 ) 10
( 0 2 ) 1
( 1 2 ) 1
( 2 3 ) 1
( 3 1 ) 1


In [35]:
def rand_matr_pos_graph(n_nodes, sparse_factor, max_weight=50., decimals=0):    
    """
    """
    grafo_completo = np.random.randint(0,max_weight,(n_nodes,n_nodes))
    ramas =  np.random.binomial(1,sparse_factor,size=(n_nodes,n_nodes))  # dicta si hay ramas o no
    
        
def m_g_2_d_g(m_g):
    """
    """
    pass
    

def d_g_2_m_g(d_g):    
    """
    """
    pass

m_g = rand_matr_pos_graph(n_nodes=5, sparse_factor=0.5, max_weight=50.)    


#d_g = m_g_2_d_g(m_g)
#m_g_2 = d_g_2_m_g(d_g)

#print_m_g(m_g)

print(np.random.randint(0,10,(5,5)))
#print_d_g(d_g)
#print("\nnum_elem_iguales:\t%d" % (m_g_2 == m_g).sum() )

[[4 0 0 2 7]
 [9 1 6 8 1]
 [0 6 1 6 2]
 [9 6 9 8 4]
 [7 5 5 6 7]]
